name: bbts_server
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  provider: ^6.1.5
  pin_code_fields: ^8.0.1
  flutter_secure_storage: ^9.2.4
  flutter_native_contact_picker: ^0.0.7
  intl: ^0.20.2
  image_picker: ^1.1.2
  scan: ^1.6.0
  qr_flutter: ^4.1.0
  share_plus: ^7.0.2
  flutter_svg: ^2.0.5
  network_info_plus: ^4.0.1
  connectivity_plus:
  permission_handler: ^10.4.2
  open_settings: ^2.0.2
  dio: ^5.8.0+1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.2
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.1.4
  fluttertoast: ^8.2.8
  sleek_circular_slider: ^2.0.1
  font_awesome_flutter: 10.6.0
  geolocator: ^12.0.0
  carousel_slider: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/BBT_LOGO_2.png"
  min_sdk_android: 21